const initState = {
    products: [
        {id: 1, name: "t-shirt_1", image: "t-shirt_1.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 2, name: "t-shirt_2", image: "t-shirt_2.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 3, name: "t-shirt_3", image: "t-shirt_3.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 4, name: "t-shirt_4", image: "t-shirt_4.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 5, name: "t-shirt_5", image: "t-shirt_5.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 6, name: "t-shirt_6", image: "t-shirt_6.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 7, name: "t-shirt_7", image: "t-shirt_7.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 8, name: "t-shirt_8", image: "t-shirt_8.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 9, name: "t-shirt_9", image: "t-shirt_9.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 10, name: "t-shirt_10", image: "t-shirt_10.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 11, name: "t-shirt_11", image: "t-shirt_11.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 12, name: "t-shirt_12", image: "t-shirt_12.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 13, name: "t-shirt_13", image: "t-shirt_13.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 14, name: "t-shirt_14", image: "t-shirt_14.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 15, name: "t-shirt_15", image: "t-shirt_15.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 16, name: "t-shirt_16", image: "t-shirt_16.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 17, name: "t-shirt_17", image: "t-shirt_17.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 18, name: "t-shirt_18", image: "t-shirt_18.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 19, name: "t-shirt_19", image: "t-shirt_19.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
        {id: 20, name: "t-shirt_20", image: "t-shirt_20.webp", price: 20, discount: 2, discountPrice: 20 - 20 * 0.02, quantity: 1, desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore corporis obcaecati fuga dicta, error sunt! Dolor libero incidunt beatae, tempora fugiat hic quae eius adipisci! Minima excepturi totam iste error."},
    ],
    product: {}
}
const ProductsReducer = (state = initState, action) => {
    //console.log(typeof action.id) // Dobijamo string
    switch(action.type) {
        case "PRODUCT":
            return {...state, product: state.products.find(product => product.id === parseInt(action.id))}
        default:
        return state;
    }
}

export default ProductsReducer;